name: CI integration



on : # event register

  push: # event
    branches: # which branches
    - main



jobs:

  build: # job id
    runs-on: "ubuntu-latest"
    steps: 
      # - name: first human
      - run: echo "starting a ci workflow in action"
      - run: echo "this workflow is now running ${{runner.os}}"
      - run: echo "py version"
      - run: python --version

      
      - name: checking github env
        run: echo "${{toJson(github)}}"

      - name: "checkout the repo in vm"
        uses: action/checkout@v5

      - name: listing current dir
        run: ls

      # configure using requirement file
      - name: generating a requirement file
        run: "python -m "
      

    # linitng
    
    # checking security auditing
    
    # static analysis

    # license auditing

    # testing
      - name: "demo"
        run : "echo 'unreachable'"

      
      - run: pipenv run pytest


