name: CI integration
on :
  push:
    branches: 
    - main

jobs:
  firstPhase: # job id
    runs-on: "ubuntu-latest"
    steps: 
      # - name: first human
      - run: echo "starting a ci workflow in action"
      - run: echo "this workflow is now running ${{runner.os}}"
      - run: echo "py version" 
      - run: python --version
      # - run: echo "${{toJson(github)}}"
      - run: pip install pipenv
      # configure
      - run: pipenv shell
      # linitng
      
      # checking auditing
      
      # testing
      - run: pytest

