name: CI integration
on :
  - push

jobs:
  firstPhase: # job id
    runs-on: "ubuntu-latest"
    steps: 
      # - name: first human
      - run: echo "starting a ci workflow in action"
      - run: echo "this workflow is now running ${{runner.os}}"
      - run: echo "${{github}}"
