name: CI integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install pipenv and dependencies
        run: |
          export PIPENV_VENV_IN_PROJECT=1
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --ignore-pipfile

      - name: List current directory
        run: ls && echo $PIPENV_VENV_IN_PROJECT

      - name: Upload venv as artifact
        uses: actions/upload-artifact@v4
        with:
          name: py-venv
          path: .venv/
          retention-days: 1

  testing:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Download venv artifact
        uses: actions/download-artifact@v4
        with:
          name: py-venv
          path: .venv

      - name: Run tests
        run: pipenv run pytest -v
